version: '2'

services:

  postgres:
    image: 'postgres'
    container_name: 'postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=my_db'
    expose:
      - "5433"
    ports:
      - "5433:5433"
    command: -p 5433

  app:
    image: 'seven_winds:latest'
    container_name: 'app'
    build:
      context: .
    depends_on:
      - 'postgres'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5433/my_db'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=postgres'
    expose:
      - "8080"
    ports:
      - "8080:8080"
